### ISSUE TITLE
Comply with latest delta-sharing protocol

### ISSUE THREAD

**Issue by tmnd1991** [agile-lab-dev/whitefox#94]
Our copy of delta-sharing protocol markdown, api and implementation are synced with revision:
e19f640fd3f4881547d72164ce24cb754cbdd0be we should sync to the latest revision.

This will be split in multiple PRs:

- [x] update openapi spec and written form (94-1 - #203)
- [x] support of delta-sharing-capabilities header (94-2 - #201 )
- [ ] fail when delta is needed but not supported (94-3 #222)
- [ ] support delta format (94-4)
